from domus.utils.config import INFLUX_DB_PASSWORD,INFLUX_DB_SERVER,INFLUX_DB_PASSWORD,INFLUX_DB_TABLE,INFLUX_DB_USER

JOB_STORAGE =  'mysql://{}:{}@{}/{}'.format(
    INFLUX_DB_USER,
    INFLUX_DB_PASSWORD,
    INFLUX_DB_SERVER,
    INFLUX_DB_TABLE)